grunt lint added in pre commit

diff --git a/contrib/pre-commit b/contrib/pre-commit
--- a/contrib/pre-commit
+++ b/contrib/pre-commit
@@ -37,4 +37,11 @@ then
 	fi
 fi
 
+echo "Running Grunt..."
+grunt pre-commit
+if [ $? -ne 0 ]; then
+ echo "Grunt failed, please fix code and recommit"
+ exit 1
+fi
+
 exit $?
